version: '3.3'

services:
  db:
    image: postgres:10.1-alpine
  backend:
    image: badchess/backend:latest
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "7001:80"
    depends_on:
      - db
  frontend:
    image: badchess/frontend:latest
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "7000:80"
  nginx:
    image: badchess/nginx:latest
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
  
